subcomponents:
  sample-service:
    config:
      image:
        tag: master-20200325.1
      service:
        dns: sample.contoso.com
      configMap:
        DB_CONNECTION_STRING: "postgres://unicef-prod.postgresql.azure.com/db"
      replicas: 3
